# Generated by Django 5.1.3 on 2024-11-08 06:18

import apps.general.unique_id
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_generate', models.CharField(default=apps.general.unique_id.generate_unique_id, editable=False, max_length=8, unique=True)),
                ('name', models.CharField(max_length=700)),
                ('price', models.DecimalField(decimal_places=2, max_digits=20)),
                ('description', models.TextField()),
                ('video_url', models.URLField(blank=True, null=True)),
                ('in_stock', models.PositiveSmallIntegerField(default=0)),
                ('admin_money', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('delivery_price', models.PositiveIntegerField(default=30000)),
                ('is_active', models.BooleanField(default=True)),
                ('like_counts', models.IntegerField(default=0)),
                ('view_counts', models.IntegerField(default=0)),
                ('comment_counts', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('main_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='products', to='categories.category')),
                ('sub_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='products', to='categories.subcategory')),
            ],
            options={
                'db_table': 'product',
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='discount/images/%Y/%m/%d/')),
                ('ordering_number', models.PositiveSmallIntegerField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
        ),
    ]
