# Generated by Django 5.1.3 on 2024-11-08 06:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(1, 'YANGI'), (2, 'DASTAVKAGA_TAYYOR'), (3, 'YETKAZILMOQDA'), (4, 'QAYTA_QUNGIROQ'), (5, 'YETKAZIB_BERILDI')], default=1)),
                ('admin_money', models.DecimalField(decimal_places=2, max_digits=20)),
                ('product_count', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('buyer_name', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=13, validators=[django.core.validators.RegexValidator(code='uzb_phone_number_validation', message='Example: +998 XXXXXXXXX', regex='^\\+998\\d{9}$')])),
                ('area', models.IntegerField(choices=[(1, 'Toshkent'), (14, 'Qoraqalpogiston'), (11, 'Qashqadaryo'), (2, 'Sirdaryo'), (3, 'Jizzax'), (5, 'Fargona'), (6, 'Namangan'), (7, 'Andijon'), (8, 'Buxoro'), (9, 'Xorazm'), (10, 'Navoiy'), (12, 'Surxondaryo'), (13, 'Samarqand')])),
                ('order_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
