# Generated by Django 5.1.3 on 2024-11-08 06:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('likes', '0001_initial'),
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='productdislike',
            name='user',
            field=models.ForeignKey(limit_choices_to={'is_active': True, 'is_deleted': False}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dislikes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='productlike',
            name='product',
            field=models.ForeignKey(limit_choices_to={'is_active': True}, on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='products.product'),
        ),
        migrations.AddField(
            model_name='productlike',
            name='user',
            field=models.ForeignKey(limit_choices_to={'is_active': True, 'is_deleted': False}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='likes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='productlike',
            unique_together={('user', 'product')},
        ),
    ]
