# Generated by Django 5.1.3 on 2024-11-18 09:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='General',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=1000)),
                ('logo', models.ImageField(upload_to='general_logo/')),
                ('banner', models.ImageField(upload_to='general_banner/')),
                ('email', models.EmailField(max_length=100)),
                ('phone_number', models.CharField(max_length=13, unique=True, validators=[django.core.validators.RegexValidator(code='uzb_phone_number_validation', message='Example: +998 XXXXXXXXX', regex='^\\+998\\d{9}$')])),
                ('sayt_url', models.URLField(max_length=100)),
                ('telegram_url', models.URLField(max_length=100)),
                ('instagram_url', models.URLField(max_length=100)),
                ('facebook_url', models.URLField(max_length=100)),
                ('youtube_url', models.URLField(max_length=100)),
            ],
        ),
    ]
